### ISSUE TITLE
feat: RoadMap to v4

### ISSUE THREAD

**Issue by retraigo** [nekooftheabyss/duration.js#18]
- [x] Simplify `getFormattedDuration`.
- [x] Replace `getSimpleFormattedDuration` with `toString`.
- [x] Remove `getSimpleFormattedDuration`.
- [ ] Replace `getFormattedDuration` with `format`.
- [x] Remove `getFormattedDuration`.
- [ ] Replace `stringify` with `format`.
- [x] Remove `stringify`.

**Comment by retraigo** [comment]
`stringify` and `getFormattedDuration` have been replaced with #20. Closing this.
